// Generated by scripts/generate-zh-hints.mjs. Do not edit by hand.
export const ZH_HINT_METADATA = {
  "学生": {
    "pinyinInitials": [
      "x",
      "sh"
    ],
    "tones": [
      2,
      5
    ],
    "meaning": "a person enrolled in a course of learning",
    "firstCharacter": "学"
  },
  "学校": {
    "pinyinInitials": [
      "x",
      "x"
    ],
    "tones": [
      2,
      4
    ],
    "meaning": "an institution where people receive education",
    "firstCharacter": "学"
  },
  "老师": {
    "pinyinInitials": [
      "l",
      "sh"
    ],
    "tones": [
      3,
      1
    ],
    "meaning": "a person whose role is teaching others",
    "firstCharacter": "老"
  },
  "朋友": {
    "pinyinInitials": [
      "p",
      "y"
    ],
    "tones": [
      2,
      5
    ],
    "meaning": "someone joined to another by mutual affection",
    "firstCharacter": "朋"
  },
  "工作": {
    "pinyinInitials": [
      "g",
      "z"
    ],
    "tones": [
      1,
      4
    ],
    "meaning": "an activity or role involving regular labor",
    "firstCharacter": "工"
  },
  "时间": {
    "pinyinInitials": [
      "sh",
      "j"
    ],
    "tones": [
      2,
      1
    ],
    "meaning": "the measured progression or duration of events",
    "firstCharacter": "时"
  },
  "今天": {
    "pinyinInitials": [
      "j",
      "t"
    ],
    "tones": [
      1,
      1
    ],
    "meaning": "the current calendar day",
    "firstCharacter": "今"
  },
  "明天": {
    "pinyinInitials": [
      "m",
      "t"
    ],
    "tones": [
      2,
      1
    ],
    "meaning": "the calendar day following the current one",
    "firstCharacter": "明"
  },
  "昨天": {
    "pinyinInitials": [
      "z",
      "t"
    ],
    "tones": [
      2,
      1
    ],
    "meaning": "the calendar day preceding the current one",
    "firstCharacter": "昨"
  },
  "现在": {
    "pinyinInitials": [
      "x",
      "z"
    ],
    "tones": [
      4,
      4
    ],
    "meaning": "at the present moment",
    "firstCharacter": "现"
  },
  "这里": {
    "pinyinInitials": [
      "zh",
      "l"
    ],
    "tones": [
      4,
      3
    ],
    "meaning": "a location close to the speaker",
    "firstCharacter": "这"
  },
  "那里": {
    "pinyinInitials": [
      "n",
      "l"
    ],
    "tones": [
      4,
      5
    ],
    "meaning": "a location away from the speaker",
    "firstCharacter": "那"
  },
  "家庭": {
    "pinyinInitials": [
      "j",
      "t"
    ],
    "tones": [
      1,
      2
    ],
    "meaning": "a household or group of related people",
    "firstCharacter": "家"
  },
  "父亲": {
    "pinyinInitials": [
      "f",
      "q"
    ],
    "tones": [
      4,
      1
    ],
    "meaning": "a male parent",
    "firstCharacter": "父"
  },
  "母亲": {
    "pinyinInitials": [
      "m",
      "q"
    ],
    "tones": [
      3,
      1
    ],
    "meaning": "a female parent",
    "firstCharacter": "母"
  },
  "哥哥": {
    "pinyinInitials": [
      "g",
      "g"
    ],
    "tones": [
      1,
      5
    ],
    "meaning": "an older male sibling",
    "firstCharacter": "哥"
  },
  "姐姐": {
    "pinyinInitials": [
      "j",
      "j"
    ],
    "tones": [
      3,
      5
    ],
    "meaning": "an older female sibling",
    "firstCharacter": "姐"
  },
  "弟弟": {
    "pinyinInitials": [
      "d",
      "d"
    ],
    "tones": [
      4,
      5
    ],
    "meaning": "a younger male sibling",
    "firstCharacter": "弟"
  },
  "妹妹": {
    "pinyinInitials": [
      "m",
      "m"
    ],
    "tones": [
      4,
      5
    ],
    "meaning": "a younger female sibling",
    "firstCharacter": "妹"
  },
  "儿子": {
    "pinyinInitials": [
      "∅",
      "z"
    ],
    "tones": [
      2,
      5
    ],
    "meaning": "a male child in relation to a parent",
    "firstCharacter": "儿"
  },
  "女儿": {
    "pinyinInitials": [
      "n",
      "∅"
    ],
    "tones": [
      3,
      2
    ],
    "meaning": "a female child in relation to a parent",
    "firstCharacter": "女"
  },
  "男人": {
    "pinyinInitials": [
      "n",
      "r"
    ],
    "tones": [
      2,
      2
    ],
    "meaning": "an adult male person",
    "firstCharacter": "男"
  },
  "女人": {
    "pinyinInitials": [
      "n",
      "r"
    ],
    "tones": [
      3,
      2
    ],
    "meaning": "an adult female person",
    "firstCharacter": "女"
  },
  "孩子": {
    "pinyinInitials": [
      "h",
      "z"
    ],
    "tones": [
      2,
      5
    ],
    "meaning": "a young person or someone's offspring",
    "firstCharacter": "孩"
  },
  "早上": {
    "pinyinInitials": [
      "z",
      "sh"
    ],
    "tones": [
      3,
      5
    ],
    "meaning": "the early part of the day",
    "firstCharacter": "早"
  },
  "晚上": {
    "pinyinInitials": [
      "w",
      "sh"
    ],
    "tones": [
      3,
      5
    ],
    "meaning": "the later part of the day or night",
    "firstCharacter": "晚"
  },
  "中午": {
    "pinyinInitials": [
      "zh",
      "w"
    ],
    "tones": [
      1,
      3
    ],
    "meaning": "the middle of the day around noon",
    "firstCharacter": "中"
  },
  "今年": {
    "pinyinInitials": [
      "j",
      "n"
    ],
    "tones": [
      1,
      2
    ],
    "meaning": "the current calendar year",
    "firstCharacter": "今"
  },
  "去年": {
    "pinyinInitials": [
      "q",
      "n"
    ],
    "tones": [
      4,
      2
    ],
    "meaning": "the calendar year immediately before this one",
    "firstCharacter": "去"
  },
  "明年": {
    "pinyinInitials": [
      "m",
      "n"
    ],
    "tones": [
      2,
      2
    ],
    "meaning": "the calendar year immediately after this one",
    "firstCharacter": "明"
  },
  "天气": {
    "pinyinInitials": [
      "t",
      "q"
    ],
    "tones": [
      1,
      4
    ],
    "meaning": "the condition of the atmosphere at a place",
    "firstCharacter": "天"
  },
  "太阳": {
    "pinyinInitials": [
      "t",
      "y"
    ],
    "tones": [
      4,
      5
    ],
    "meaning": "the star at the center of our solar system",
    "firstCharacter": "太"
  },
  "月亮": {
    "pinyinInitials": [
      "y",
      "l"
    ],
    "tones": [
      4,
      5
    ],
    "meaning": "Earth's natural satellite seen in the night sky",
    "firstCharacter": "月"
  },
  "水果": {
    "pinyinInitials": [
      "sh",
      "g"
    ],
    "tones": [
      3,
      3
    ],
    "meaning": "edible plant produce that is often sweet",
    "firstCharacter": "水"
  },
  "苹果": {
    "pinyinInitials": [
      "p",
      "g"
    ],
    "tones": [
      2,
      3
    ],
    "meaning": "a firm round fruit that grows on trees",
    "firstCharacter": "苹"
  },
  "香蕉": {
    "pinyinInitials": [
      "x",
      "j"
    ],
    "tones": [
      1,
      1
    ],
    "meaning": "a long curved tropical fruit with soft flesh",
    "firstCharacter": "香"
  },
  "西瓜": {
    "pinyinInitials": [
      "x",
      "g"
    ],
    "tones": [
      1,
      1
    ],
    "meaning": "a large green-rinded fruit with a juicy interior",
    "firstCharacter": "西"
  },
  "米饭": {
    "pinyinInitials": [
      "m",
      "f"
    ],
    "tones": [
      3,
      4
    ],
    "meaning": "cooked grain commonly served as a staple food",
    "firstCharacter": "米"
  },
  "面包": {
    "pinyinInitials": [
      "m",
      "b"
    ],
    "tones": [
      4,
      1
    ],
    "meaning": "a baked food usually made from flour",
    "firstCharacter": "面"
  },
  "牛奶": {
    "pinyinInitials": [
      "n",
      "n"
    ],
    "tones": [
      2,
      3
    ],
    "meaning": "a dairy liquid produced by cows",
    "firstCharacter": "牛"
  },
  "咖啡": {
    "pinyinInitials": [
      "k",
      "f"
    ],
    "tones": [
      1,
      1
    ],
    "meaning": "a drink brewed from roasted beans",
    "firstCharacter": "咖"
  },
  "电脑": {
    "pinyinInitials": [
      "d",
      "n"
    ],
    "tones": [
      4,
      3
    ],
    "meaning": "an electronic device that processes information",
    "firstCharacter": "电"
  },
  "手机": {
    "pinyinInitials": [
      "sh",
      "j"
    ],
    "tones": [
      3,
      1
    ],
    "meaning": "a handheld device for mobile communication",
    "firstCharacter": "手"
  },
  "电视": {
    "pinyinInitials": [
      "d",
      "sh"
    ],
    "tones": [
      4,
      4
    ],
    "meaning": "a medium or device for broadcast moving images",
    "firstCharacter": "电"
  },
  "电影": {
    "pinyinInitials": [
      "d",
      "y"
    ],
    "tones": [
      4,
      3
    ],
    "meaning": "a story or production recorded as moving images",
    "firstCharacter": "电"
  },
  "音乐": {
    "pinyinInitials": [
      "y",
      "y"
    ],
    "tones": [
      1,
      4
    ],
    "meaning": "organized sound created for expression or enjoyment",
    "firstCharacter": "音"
  },
  "运动": {
    "pinyinInitials": [
      "y",
      "d"
    ],
    "tones": [
      4,
      4
    ],
    "meaning": "physical activity performed for exercise or competition",
    "firstCharacter": "运"
  },
  "足球": {
    "pinyinInitials": [
      "z",
      "q"
    ],
    "tones": [
      2,
      2
    ],
    "meaning": "a team sport centered on kicking a ball toward a goal",
    "firstCharacter": "足"
  },
  "篮球": {
    "pinyinInitials": [
      "l",
      "q"
    ],
    "tones": [
      2,
      2
    ],
    "meaning": "a team sport centered on shooting into a raised hoop",
    "firstCharacter": "篮"
  },
  "颜色": {
    "pinyinInitials": [
      "y",
      "s"
    ],
    "tones": [
      2,
      4
    ],
    "meaning": "a visual property determined by reflected light",
    "firstCharacter": "颜"
  },
  "红色": {
    "pinyinInitials": [
      "h",
      "s"
    ],
    "tones": [
      2,
      4
    ],
    "meaning": "a warm primary color associated with fire",
    "firstCharacter": "红"
  },
  "白色": {
    "pinyinInitials": [
      "b",
      "s"
    ],
    "tones": [
      2,
      4
    ],
    "meaning": "the lightest color, associated with snow",
    "firstCharacter": "白"
  },
  "黑色": {
    "pinyinInitials": [
      "h",
      "s"
    ],
    "tones": [
      1,
      4
    ],
    "meaning": "the darkest color, associated with an absence of light",
    "firstCharacter": "黑"
  },
  "蓝色": {
    "pinyinInitials": [
      "l",
      "s"
    ],
    "tones": [
      2,
      4
    ],
    "meaning": "a cool primary color associated with a clear sky",
    "firstCharacter": "蓝"
  },
  "绿色": {
    "pinyinInitials": [
      "l",
      "s"
    ],
    "tones": [
      4,
      4
    ],
    "meaning": "a color strongly associated with growing plants",
    "firstCharacter": "绿"
  },
  "大学": {
    "pinyinInitials": [
      "d",
      "x"
    ],
    "tones": [
      4,
      2
    ],
    "meaning": "an institution providing advanced education",
    "firstCharacter": "大"
  },
  "医生": {
    "pinyinInitials": [
      "y",
      "sh"
    ],
    "tones": [
      1,
      1
    ],
    "meaning": "a trained professional who provides medical care",
    "firstCharacter": "医"
  },
  "医院": {
    "pinyinInitials": [
      "y",
      "y"
    ],
    "tones": [
      1,
      4
    ],
    "meaning": "a facility where people receive medical treatment",
    "firstCharacter": "医"
  },
  "公司": {
    "pinyinInitials": [
      "g",
      "s"
    ],
    "tones": [
      1,
      1
    ],
    "meaning": "an organization formed to conduct business",
    "firstCharacter": "公"
  },
  "商店": {
    "pinyinInitials": [
      "sh",
      "d"
    ],
    "tones": [
      1,
      4
    ],
    "meaning": "a place where goods are offered for sale",
    "firstCharacter": "商"
  },
  "饭店": {
    "pinyinInitials": [
      "f",
      "d"
    ],
    "tones": [
      4,
      4
    ],
    "meaning": "a business serving prepared meals, sometimes with lodging",
    "firstCharacter": "饭"
  },
  "机场": {
    "pinyinInitials": [
      "j",
      "ch"
    ],
    "tones": [
      1,
      3
    ],
    "meaning": "a place where aircraft take off and land",
    "firstCharacter": "机"
  },
  "火车": {
    "pinyinInitials": [
      "h",
      "ch"
    ],
    "tones": [
      3,
      1
    ],
    "meaning": "a connected rail vehicle used for transportation",
    "firstCharacter": "火"
  },
  "汽车": {
    "pinyinInitials": [
      "q",
      "ch"
    ],
    "tones": [
      4,
      1
    ],
    "meaning": "a road vehicle powered by an engine",
    "firstCharacter": "汽"
  }
} as const;
