// Generated by scripts/generate-zh-pinyin-catalog.mjs. Do not edit by hand.
import { ZH_PINYIN_GUESS_KEYS_4 } from './zhPinyinGuessKeyShards/4.generated.js';
import { ZH_PINYIN_GUESS_KEYS_5 } from './zhPinyinGuessKeyShards/5.generated.js';
import { ZH_PINYIN_GUESS_KEYS_6 } from './zhPinyinGuessKeyShards/6.generated.js';
import { ZH_PINYIN_GUESS_KEYS_7 } from './zhPinyinGuessKeyShards/7.generated.js';
import { ZH_PINYIN_GUESS_KEYS_8 } from './zhPinyinGuessKeyShards/8.generated.js';
import { ZH_PINYIN_GUESS_KEYS_9 } from './zhPinyinGuessKeyShards/9.generated.js';

export const ZH_PINYIN_GUESS_KEYS_BY_LENGTH: Readonly<Record<number, readonly string[]>> = {
  4: ZH_PINYIN_GUESS_KEYS_4,
  5: ZH_PINYIN_GUESS_KEYS_5,
  6: ZH_PINYIN_GUESS_KEYS_6,
  7: ZH_PINYIN_GUESS_KEYS_7,
  8: ZH_PINYIN_GUESS_KEYS_8,
  9: ZH_PINYIN_GUESS_KEYS_9,
};

export function isValidChinesePinyinGuessKey(key: string, length = key.length): boolean {
  return ZH_PINYIN_GUESS_KEYS_BY_LENGTH[length]?.includes(key) ?? false;
}
