// Generated by scripts/generate-zh-pinyin-catalog.mjs. Do not edit by hand.
export const ZH_PINYIN_PUZZLE_ANSWERS = [
  {
    "id": "学生",
    "hanzi": "学生",
    "key": "xuesheng",
    "pinyinMarked": "xué sheng",
    "pinyinNumeric": "xue2 sheng5",
    "tones": [
      2,
      5
    ],
    "syllableBoundary": 3,
    "broadMeaning": "a person enrolled in a course of learning",
    "length": 8,
    "answerEligible": true
  },
  {
    "id": "学校",
    "hanzi": "学校",
    "key": "xuexiao",
    "pinyinMarked": "xué xiào",
    "pinyinNumeric": "xue2 xiao4",
    "tones": [
      2,
      4
    ],
    "syllableBoundary": 3,
    "broadMeaning": "an institution where people receive education",
    "length": 7,
    "answerEligible": true
  },
  {
    "id": "老师",
    "hanzi": "老师",
    "key": "laoshi",
    "pinyinMarked": "lǎo shī",
    "pinyinNumeric": "lao3 shi1",
    "tones": [
      3,
      1
    ],
    "syllableBoundary": 3,
    "broadMeaning": "a person whose role is teaching others",
    "length": 6,
    "answerEligible": true
  },
  {
    "id": "朋友",
    "hanzi": "朋友",
    "key": "pengyou",
    "pinyinMarked": "péng you",
    "pinyinNumeric": "peng2 you5",
    "tones": [
      2,
      5
    ],
    "syllableBoundary": 4,
    "broadMeaning": "someone joined to another by mutual affection",
    "length": 7,
    "answerEligible": true
  },
  {
    "id": "工作",
    "hanzi": "工作",
    "key": "gongzuo",
    "pinyinMarked": "gōng zuò",
    "pinyinNumeric": "gong1 zuo4",
    "tones": [
      1,
      4
    ],
    "syllableBoundary": 4,
    "broadMeaning": "an activity or role involving regular labor",
    "length": 7,
    "answerEligible": true
  },
  {
    "id": "时间",
    "hanzi": "时间",
    "key": "shijian",
    "pinyinMarked": "shí jiān",
    "pinyinNumeric": "shi2 jian1",
    "tones": [
      2,
      1
    ],
    "syllableBoundary": 3,
    "broadMeaning": "the measured progression or duration of events",
    "length": 7,
    "answerEligible": true
  },
  {
    "id": "今天",
    "hanzi": "今天",
    "key": "jintian",
    "pinyinMarked": "jīn tiān",
    "pinyinNumeric": "jin1 tian1",
    "tones": [
      1,
      1
    ],
    "syllableBoundary": 3,
    "broadMeaning": "the current calendar day",
    "length": 7,
    "answerEligible": true
  },
  {
    "id": "明天",
    "hanzi": "明天",
    "key": "mingtian",
    "pinyinMarked": "míng tiān",
    "pinyinNumeric": "ming2 tian1",
    "tones": [
      2,
      1
    ],
    "syllableBoundary": 4,
    "broadMeaning": "the calendar day following the current one",
    "length": 8,
    "answerEligible": true
  },
  {
    "id": "昨天",
    "hanzi": "昨天",
    "key": "zuotian",
    "pinyinMarked": "zuó tiān",
    "pinyinNumeric": "zuo2 tian1",
    "tones": [
      2,
      1
    ],
    "syllableBoundary": 3,
    "broadMeaning": "the calendar day preceding the current one",
    "length": 7,
    "answerEligible": true
  },
  {
    "id": "现在",
    "hanzi": "现在",
    "key": "xianzai",
    "pinyinMarked": "xiàn zài",
    "pinyinNumeric": "xian4 zai4",
    "tones": [
      4,
      4
    ],
    "syllableBoundary": 4,
    "broadMeaning": "at the present moment",
    "length": 7,
    "answerEligible": true
  },
  {
    "id": "这里",
    "hanzi": "这里",
    "key": "zheli",
    "pinyinMarked": "zhè lǐ",
    "pinyinNumeric": "zhe4 li3",
    "tones": [
      4,
      3
    ],
    "syllableBoundary": 3,
    "broadMeaning": "a location close to the speaker",
    "length": 5,
    "answerEligible": true
  },
  {
    "id": "那里",
    "hanzi": "那里",
    "key": "nali",
    "pinyinMarked": "nà li",
    "pinyinNumeric": "na4 li5",
    "tones": [
      4,
      5
    ],
    "syllableBoundary": 2,
    "broadMeaning": "a location away from the speaker",
    "length": 4,
    "answerEligible": true
  },
  {
    "id": "家庭",
    "hanzi": "家庭",
    "key": "jiating",
    "pinyinMarked": "jiā tíng",
    "pinyinNumeric": "jia1 ting2",
    "tones": [
      1,
      2
    ],
    "syllableBoundary": 3,
    "broadMeaning": "a household or group of related people",
    "length": 7,
    "answerEligible": true
  },
  {
    "id": "父亲",
    "hanzi": "父亲",
    "key": "fuqin",
    "pinyinMarked": "fù qīn",
    "pinyinNumeric": "fu4 qin1",
    "tones": [
      4,
      1
    ],
    "syllableBoundary": 2,
    "broadMeaning": "a male parent",
    "length": 5,
    "answerEligible": true
  },
  {
    "id": "母亲",
    "hanzi": "母亲",
    "key": "muqin",
    "pinyinMarked": "mǔ qīn",
    "pinyinNumeric": "mu3 qin1",
    "tones": [
      3,
      1
    ],
    "syllableBoundary": 2,
    "broadMeaning": "a female parent",
    "length": 5,
    "answerEligible": true
  },
  {
    "id": "哥哥",
    "hanzi": "哥哥",
    "key": "gege",
    "pinyinMarked": "gē ge",
    "pinyinNumeric": "ge1 ge5",
    "tones": [
      1,
      5
    ],
    "syllableBoundary": 2,
    "broadMeaning": "an older male sibling",
    "length": 4,
    "answerEligible": true
  },
  {
    "id": "姐姐",
    "hanzi": "姐姐",
    "key": "jiejie",
    "pinyinMarked": "jiě jie",
    "pinyinNumeric": "jie3 jie5",
    "tones": [
      3,
      5
    ],
    "syllableBoundary": 3,
    "broadMeaning": "an older female sibling",
    "length": 6,
    "answerEligible": true
  },
  {
    "id": "弟弟",
    "hanzi": "弟弟",
    "key": "didi",
    "pinyinMarked": "dì di",
    "pinyinNumeric": "di4 di5",
    "tones": [
      4,
      5
    ],
    "syllableBoundary": 2,
    "broadMeaning": "a younger male sibling",
    "length": 4,
    "answerEligible": true
  },
  {
    "id": "妹妹",
    "hanzi": "妹妹",
    "key": "meimei",
    "pinyinMarked": "mèi mei",
    "pinyinNumeric": "mei4 mei5",
    "tones": [
      4,
      5
    ],
    "syllableBoundary": 3,
    "broadMeaning": "a younger female sibling",
    "length": 6,
    "answerEligible": true
  },
  {
    "id": "儿子",
    "hanzi": "儿子",
    "key": "erzi",
    "pinyinMarked": "ér zi",
    "pinyinNumeric": "er2 zi5",
    "tones": [
      2,
      5
    ],
    "syllableBoundary": 2,
    "broadMeaning": "a male child in relation to a parent",
    "length": 4,
    "answerEligible": true
  },
  {
    "id": "女儿",
    "hanzi": "女儿",
    "key": "nver",
    "pinyinMarked": "nǚ ér",
    "pinyinNumeric": "nu:3 er2",
    "tones": [
      3,
      2
    ],
    "syllableBoundary": 2,
    "broadMeaning": "a female child in relation to a parent",
    "length": 4,
    "answerEligible": true
  },
  {
    "id": "男人",
    "hanzi": "男人",
    "key": "nanren",
    "pinyinMarked": "nán rén",
    "pinyinNumeric": "nan2 ren2",
    "tones": [
      2,
      2
    ],
    "syllableBoundary": 3,
    "broadMeaning": "an adult male person",
    "length": 6,
    "answerEligible": true
  },
  {
    "id": "女人",
    "hanzi": "女人",
    "key": "nvren",
    "pinyinMarked": "nǚ rén",
    "pinyinNumeric": "nu:3 ren2",
    "tones": [
      3,
      2
    ],
    "syllableBoundary": 2,
    "broadMeaning": "an adult female person",
    "length": 5,
    "answerEligible": true
  },
  {
    "id": "孩子",
    "hanzi": "孩子",
    "key": "haizi",
    "pinyinMarked": "hái zi",
    "pinyinNumeric": "hai2 zi5",
    "tones": [
      2,
      5
    ],
    "syllableBoundary": 3,
    "broadMeaning": "a young person or someone's offspring",
    "length": 5,
    "answerEligible": true
  },
  {
    "id": "早上",
    "hanzi": "早上",
    "key": "zaoshang",
    "pinyinMarked": "zǎo shang",
    "pinyinNumeric": "zao3 shang5",
    "tones": [
      3,
      5
    ],
    "syllableBoundary": 3,
    "broadMeaning": "the early part of the day",
    "length": 8,
    "answerEligible": true
  },
  {
    "id": "晚上",
    "hanzi": "晚上",
    "key": "wanshang",
    "pinyinMarked": "wǎn shang",
    "pinyinNumeric": "wan3 shang5",
    "tones": [
      3,
      5
    ],
    "syllableBoundary": 3,
    "broadMeaning": "the later part of the day or night",
    "length": 8,
    "answerEligible": true
  },
  {
    "id": "中午",
    "hanzi": "中午",
    "key": "zhongwu",
    "pinyinMarked": "zhōng wǔ",
    "pinyinNumeric": "zhong1 wu3",
    "tones": [
      1,
      3
    ],
    "syllableBoundary": 5,
    "broadMeaning": "the middle of the day around noon",
    "length": 7,
    "answerEligible": true
  },
  {
    "id": "今年",
    "hanzi": "今年",
    "key": "jinnian",
    "pinyinMarked": "jīn nián",
    "pinyinNumeric": "jin1 nian2",
    "tones": [
      1,
      2
    ],
    "syllableBoundary": 3,
    "broadMeaning": "the current calendar year",
    "length": 7,
    "answerEligible": true
  },
  {
    "id": "去年",
    "hanzi": "去年",
    "key": "qunian",
    "pinyinMarked": "qù nián",
    "pinyinNumeric": "qu4 nian2",
    "tones": [
      4,
      2
    ],
    "syllableBoundary": 2,
    "broadMeaning": "the calendar year immediately before this one",
    "length": 6,
    "answerEligible": true
  },
  {
    "id": "明年",
    "hanzi": "明年",
    "key": "mingnian",
    "pinyinMarked": "míng nián",
    "pinyinNumeric": "ming2 nian2",
    "tones": [
      2,
      2
    ],
    "syllableBoundary": 4,
    "broadMeaning": "the calendar year immediately after this one",
    "length": 8,
    "answerEligible": true
  },
  {
    "id": "天气",
    "hanzi": "天气",
    "key": "tianqi",
    "pinyinMarked": "tiān qì",
    "pinyinNumeric": "tian1 qi4",
    "tones": [
      1,
      4
    ],
    "syllableBoundary": 4,
    "broadMeaning": "the condition of the atmosphere at a place",
    "length": 6,
    "answerEligible": true
  },
  {
    "id": "太阳",
    "hanzi": "太阳",
    "key": "taiyang",
    "pinyinMarked": "tài yang",
    "pinyinNumeric": "tai4 yang5",
    "tones": [
      4,
      5
    ],
    "syllableBoundary": 3,
    "broadMeaning": "the star at the center of our solar system",
    "length": 7,
    "answerEligible": true
  },
  {
    "id": "月亮",
    "hanzi": "月亮",
    "key": "yueliang",
    "pinyinMarked": "yuè liang",
    "pinyinNumeric": "yue4 liang5",
    "tones": [
      4,
      5
    ],
    "syllableBoundary": 3,
    "broadMeaning": "Earth's natural satellite seen in the night sky",
    "length": 8,
    "answerEligible": true
  },
  {
    "id": "水果",
    "hanzi": "水果",
    "key": "shuiguo",
    "pinyinMarked": "shuǐ guǒ",
    "pinyinNumeric": "shui3 guo3",
    "tones": [
      3,
      3
    ],
    "syllableBoundary": 4,
    "broadMeaning": "edible plant produce that is often sweet",
    "length": 7,
    "answerEligible": true
  },
  {
    "id": "苹果",
    "hanzi": "苹果",
    "key": "pingguo",
    "pinyinMarked": "píng guǒ",
    "pinyinNumeric": "ping2 guo3",
    "tones": [
      2,
      3
    ],
    "syllableBoundary": 4,
    "broadMeaning": "a firm round fruit that grows on trees",
    "length": 7,
    "answerEligible": true
  },
  {
    "id": "香蕉",
    "hanzi": "香蕉",
    "key": "xiangjiao",
    "pinyinMarked": "xiāng jiāo",
    "pinyinNumeric": "xiang1 jiao1",
    "tones": [
      1,
      1
    ],
    "syllableBoundary": 5,
    "broadMeaning": "a long curved tropical fruit with soft flesh",
    "length": 9,
    "answerEligible": true
  },
  {
    "id": "西瓜",
    "hanzi": "西瓜",
    "key": "xigua",
    "pinyinMarked": "xī guā",
    "pinyinNumeric": "xi1 gua1",
    "tones": [
      1,
      1
    ],
    "syllableBoundary": 2,
    "broadMeaning": "a large green-rinded fruit with a juicy interior",
    "length": 5,
    "answerEligible": true
  },
  {
    "id": "米饭",
    "hanzi": "米饭",
    "key": "mifan",
    "pinyinMarked": "mǐ fàn",
    "pinyinNumeric": "mi3 fan4",
    "tones": [
      3,
      4
    ],
    "syllableBoundary": 2,
    "broadMeaning": "cooked grain commonly served as a staple food",
    "length": 5,
    "answerEligible": true
  },
  {
    "id": "面包",
    "hanzi": "面包",
    "key": "mianbao",
    "pinyinMarked": "miàn bāo",
    "pinyinNumeric": "mian4 bao1",
    "tones": [
      4,
      1
    ],
    "syllableBoundary": 4,
    "broadMeaning": "a baked food usually made from flour",
    "length": 7,
    "answerEligible": true
  },
  {
    "id": "牛奶",
    "hanzi": "牛奶",
    "key": "niunai",
    "pinyinMarked": "niú nǎi",
    "pinyinNumeric": "niu2 nai3",
    "tones": [
      2,
      3
    ],
    "syllableBoundary": 3,
    "broadMeaning": "a dairy liquid produced by cows",
    "length": 6,
    "answerEligible": true
  },
  {
    "id": "咖啡",
    "hanzi": "咖啡",
    "key": "kafei",
    "pinyinMarked": "kā fēi",
    "pinyinNumeric": "ka1 fei1",
    "tones": [
      1,
      1
    ],
    "syllableBoundary": 2,
    "broadMeaning": "a drink brewed from roasted beans",
    "length": 5,
    "answerEligible": true
  },
  {
    "id": "电脑",
    "hanzi": "电脑",
    "key": "diannao",
    "pinyinMarked": "diàn nǎo",
    "pinyinNumeric": "dian4 nao3",
    "tones": [
      4,
      3
    ],
    "syllableBoundary": 4,
    "broadMeaning": "an electronic device that processes information",
    "length": 7,
    "answerEligible": true
  },
  {
    "id": "手机",
    "hanzi": "手机",
    "key": "shouji",
    "pinyinMarked": "shǒu jī",
    "pinyinNumeric": "shou3 ji1",
    "tones": [
      3,
      1
    ],
    "syllableBoundary": 4,
    "broadMeaning": "a handheld device for mobile communication",
    "length": 6,
    "answerEligible": true
  },
  {
    "id": "电视",
    "hanzi": "电视",
    "key": "dianshi",
    "pinyinMarked": "diàn shì",
    "pinyinNumeric": "dian4 shi4",
    "tones": [
      4,
      4
    ],
    "syllableBoundary": 4,
    "broadMeaning": "a medium or device for broadcast moving images",
    "length": 7,
    "answerEligible": true
  },
  {
    "id": "电影",
    "hanzi": "电影",
    "key": "dianying",
    "pinyinMarked": "diàn yǐng",
    "pinyinNumeric": "dian4 ying3",
    "tones": [
      4,
      3
    ],
    "syllableBoundary": 4,
    "broadMeaning": "a story or production recorded as moving images",
    "length": 8,
    "answerEligible": true
  },
  {
    "id": "音乐",
    "hanzi": "音乐",
    "key": "yinyue",
    "pinyinMarked": "yīn yuè",
    "pinyinNumeric": "yin1 yue4",
    "tones": [
      1,
      4
    ],
    "syllableBoundary": 3,
    "broadMeaning": "organized sound created for expression or enjoyment",
    "length": 6,
    "answerEligible": true
  },
  {
    "id": "运动",
    "hanzi": "运动",
    "key": "yundong",
    "pinyinMarked": "yùn dòng",
    "pinyinNumeric": "yun4 dong4",
    "tones": [
      4,
      4
    ],
    "syllableBoundary": 3,
    "broadMeaning": "physical activity performed for exercise or competition",
    "length": 7,
    "answerEligible": true
  },
  {
    "id": "足球",
    "hanzi": "足球",
    "key": "zuqiu",
    "pinyinMarked": "zú qiú",
    "pinyinNumeric": "zu2 qiu2",
    "tones": [
      2,
      2
    ],
    "syllableBoundary": 2,
    "broadMeaning": "a team sport centered on kicking a ball toward a goal",
    "length": 5,
    "answerEligible": true
  },
  {
    "id": "篮球",
    "hanzi": "篮球",
    "key": "lanqiu",
    "pinyinMarked": "lán qiú",
    "pinyinNumeric": "lan2 qiu2",
    "tones": [
      2,
      2
    ],
    "syllableBoundary": 3,
    "broadMeaning": "a team sport centered on shooting into a raised hoop",
    "length": 6,
    "answerEligible": true
  },
  {
    "id": "颜色",
    "hanzi": "颜色",
    "key": "yanse",
    "pinyinMarked": "yán sè",
    "pinyinNumeric": "yan2 se4",
    "tones": [
      2,
      4
    ],
    "syllableBoundary": 3,
    "broadMeaning": "a visual property determined by reflected light",
    "length": 5,
    "answerEligible": true
  },
  {
    "id": "红色",
    "hanzi": "红色",
    "key": "hongse",
    "pinyinMarked": "hóng sè",
    "pinyinNumeric": "hong2 se4",
    "tones": [
      2,
      4
    ],
    "syllableBoundary": 4,
    "broadMeaning": "a warm primary color associated with fire",
    "length": 6,
    "answerEligible": true
  },
  {
    "id": "白色",
    "hanzi": "白色",
    "key": "baise",
    "pinyinMarked": "bái sè",
    "pinyinNumeric": "bai2 se4",
    "tones": [
      2,
      4
    ],
    "syllableBoundary": 3,
    "broadMeaning": "the lightest color, associated with snow",
    "length": 5,
    "answerEligible": true
  },
  {
    "id": "黑色",
    "hanzi": "黑色",
    "key": "heise",
    "pinyinMarked": "hēi sè",
    "pinyinNumeric": "hei1 se4",
    "tones": [
      1,
      4
    ],
    "syllableBoundary": 3,
    "broadMeaning": "the darkest color, associated with an absence of light",
    "length": 5,
    "answerEligible": true
  },
  {
    "id": "蓝色",
    "hanzi": "蓝色",
    "key": "lanse",
    "pinyinMarked": "lán sè",
    "pinyinNumeric": "lan2 se4",
    "tones": [
      2,
      4
    ],
    "syllableBoundary": 3,
    "broadMeaning": "a cool primary color associated with a clear sky",
    "length": 5,
    "answerEligible": true
  },
  {
    "id": "绿色",
    "hanzi": "绿色",
    "key": "lvse",
    "pinyinMarked": "lǜ sè",
    "pinyinNumeric": "lu:4 se4",
    "tones": [
      4,
      4
    ],
    "syllableBoundary": 2,
    "broadMeaning": "a color strongly associated with growing plants",
    "length": 4,
    "answerEligible": true
  },
  {
    "id": "大学",
    "hanzi": "大学",
    "key": "daxue",
    "pinyinMarked": "dà xué",
    "pinyinNumeric": "da4 xue2",
    "tones": [
      4,
      2
    ],
    "syllableBoundary": 2,
    "broadMeaning": "an institution providing advanced education",
    "length": 5,
    "answerEligible": true
  },
  {
    "id": "医生",
    "hanzi": "医生",
    "key": "yisheng",
    "pinyinMarked": "yī shēng",
    "pinyinNumeric": "yi1 sheng1",
    "tones": [
      1,
      1
    ],
    "syllableBoundary": 2,
    "broadMeaning": "a trained professional who provides medical care",
    "length": 7,
    "answerEligible": true
  },
  {
    "id": "医院",
    "hanzi": "医院",
    "key": "yiyuan",
    "pinyinMarked": "yī yuàn",
    "pinyinNumeric": "yi1 yuan4",
    "tones": [
      1,
      4
    ],
    "syllableBoundary": 2,
    "broadMeaning": "a facility where people receive medical treatment",
    "length": 6,
    "answerEligible": true
  },
  {
    "id": "公司",
    "hanzi": "公司",
    "key": "gongsi",
    "pinyinMarked": "gōng sī",
    "pinyinNumeric": "gong1 si1",
    "tones": [
      1,
      1
    ],
    "syllableBoundary": 4,
    "broadMeaning": "an organization formed to conduct business",
    "length": 6,
    "answerEligible": true
  },
  {
    "id": "商店",
    "hanzi": "商店",
    "key": "shangdian",
    "pinyinMarked": "shāng diàn",
    "pinyinNumeric": "shang1 dian4",
    "tones": [
      1,
      4
    ],
    "syllableBoundary": 5,
    "broadMeaning": "a place where goods are offered for sale",
    "length": 9,
    "answerEligible": true
  },
  {
    "id": "饭店",
    "hanzi": "饭店",
    "key": "fandian",
    "pinyinMarked": "fàn diàn",
    "pinyinNumeric": "fan4 dian4",
    "tones": [
      4,
      4
    ],
    "syllableBoundary": 3,
    "broadMeaning": "a business serving prepared meals, sometimes with lodging",
    "length": 7,
    "answerEligible": true
  },
  {
    "id": "机场",
    "hanzi": "机场",
    "key": "jichang",
    "pinyinMarked": "jī chǎng",
    "pinyinNumeric": "ji1 chang3",
    "tones": [
      1,
      3
    ],
    "syllableBoundary": 2,
    "broadMeaning": "a place where aircraft take off and land",
    "length": 7,
    "answerEligible": true
  },
  {
    "id": "火车",
    "hanzi": "火车",
    "key": "huoche",
    "pinyinMarked": "huǒ chē",
    "pinyinNumeric": "huo3 che1",
    "tones": [
      3,
      1
    ],
    "syllableBoundary": 3,
    "broadMeaning": "a connected rail vehicle used for transportation",
    "length": 6,
    "answerEligible": true
  },
  {
    "id": "汽车",
    "hanzi": "汽车",
    "key": "qiche",
    "pinyinMarked": "qì chē",
    "pinyinNumeric": "qi4 che1",
    "tones": [
      4,
      1
    ],
    "syllableBoundary": 2,
    "broadMeaning": "a road vehicle powered by an engine",
    "length": 5,
    "answerEligible": true
  }
] as const;
